export const BCRYPT_ROUNDS = 12;

const EVENT_STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const RSVP_STATUS = {
  ATTENDING: "ATTENDING",
  DECLINED: "DECLINED",
  WAITLISTED: "WAITLISTED",
  PENDING: "PENDING",
};

const EMAIL_TYPE = {
  INVITE: "INVITE",
  REMINDER: "REMINDER",
  CONFIRMATION: "CONFIRMATION",
  ACCEPTANCE: "ACCEPTANCE",
  THANK_YOU: "THANKYOU",
};

const EMAIL_STATUS = {
  PENDING: "PENDING",
  SENT: "SENT",
  FAILED: "FAILED",
};

export { EVENT_STATUS, RSVP_STATUS, EMAIL_TYPE, EMAIL_STATUS };
